'use client'
import AppFooter from '@/components/AppFooter'
import AppHeader from '@/components/AppHeader'
import './styles.scss'
import { store } from '../store/store'
import { Provider } from 'react-redux'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <Provider store={store}>
          <main >
            <AppHeader />
            <div>
              {children}
            </div>
            <AppFooter />
          </main>
        </Provider>

      </body>
    </html>
  )
}
